CREATE OR REPLACE TABLE RAW_DEVOLUTIONS (
    "ID" VARCHAR NOT NULL,
    "PRODUCTO" VARCHAR,
    "USUARIO" VARCHAR,
    "BODEGA" VARCHAR,
    "CONCEPTO" VARCHAR,
    "TIPO" VARCHAR,
    "MOVIMIENTO" DOUBLE,
    "STOCK PREVIO" DOUBLE,
    "STOCK ACTUAL" DOUBLE,
    "NUMERO DE GUIA" VARCHAR,
    "ingestion_id" VARCHAR NOT NULL PRIMARY KEY,
    "ingestion_timestamp" DATETIME,
    "row_number" SMALLINT
);