CREATE OR REPLACE TABLE DEVOLUTION (
    "ID" VARCHAR NOT NULL,
    "PRODUCTO" VARCHAR,
    "USUARIO" VARCHAR,
    "BODEGA" VARCHAR,
    "CONCEPTO" VARCHAR,
    "TIPO" VARCHAR,
    "MOVIMIENTO" DOUBLE,
    "STOCK PREVIO" DOUBLE,
    "STOCK ACTUAL" DOUBLE,
    "NUMERO DE GUIA" VARCHAR,
    "fecha" DATE,
    "update_at" TIMESTAMP
);