CREATE  OR REPLACE TABLE WALLET (
    "ID" VARCHAR NOT NULL,
    "FECHA" DATE, 
    "TIPO" VARCHAR,
    "MONTO" DOUBLE,
    "MONTO PREVIO" DOUBLE,
    "ORDEN ID" VARCHAR,
    "NUMERO DE GUIA" VARCHAR,
    "DESCRIPCIÓN" VARCHAR,
    "USUARIO QUE REALIZA EL MOVIMIENTO" VARCHAR,
    "CUENTA" VARCHAR,
    "CONCEPTO DE RETIRO" VARCHAR,
    "update_at" TIMESTAMP
);