CREATE  OR REPLACE TABLE RAW_WALLET (
    "ID" VARCHAR NOT NULL,
    "FECHA" VARCHAR, 
    "TIPO" VARCHAR,
    "MONTO" DOUBLE,
    "MONTO PREVIO" DOUBLE,
    "ORDEN ID" VARCHAR,
    "NUMERO DE GUIA" VARCHAR,
    "DESCRIPCIÓN" VARCHAR,
    "USUARIO QUE REALIZA EL MOVIMIENTO" VARCHAR,
    "CUENTA" VARCHAR,
    "CONCEPTO DE RETIRO" VARCHAR,
    "ingestion_id" VARCHAR NOT NULL PRIMARY KEY,
    "ingestion_timestamp" DATETIME,
    "row_number" SMALLINT
);