INSERT INTO DEVOLUTIONS
SELECT 
"ID", 
"PRODUCTO", 
"USUARIO", 
"BODEGA", 
"CONCEPTO", 
"TIPO", 
"MOVIMIENTO", 
"STOCK PREVIO", 
"STOCK ACTUAL", 
"NUMERO DE GUIA", 
"fecha",
NOW() AS update_at
FROM df
ON CONFLICT ("ID") 
DO UPDATE SET
    "PRODUCTO" = EXCLUDED."PRODUCTO",
    "USUARIO" = EXCLUDED."USUARIO",
    "BODEGA" = EXCLUDED."BODEGA",
    "CONCEPTO" = EXCLUDED."CONCEPTO",
    "TIPO" = EXCLUDED."TIPO",
    "MOVIMIENTO" = EXCLUDED."MOVIMIENTO",
    "STOCK PREVIO" = EXCLUDED."STOCK PREVIO",
    "STOCK ACTUAL" = EXCLUDED."STOCK ACTUAL",
    "NUMERO DE GUIA" = EXCLUDED."NUMERO DE GUIA",
    "fecha" = EXCLUDED."fecha",
    "update_at" = NOW()
RETURNING *;