INSERT INTO GENERAL_SALES as t
SELECT
"ID_ORDER_PRODUCT" AS "ID",
"ID" AS "ID_ORDER", 
"HORA", 
"FECHA",
"NÚMERO GUIA", 
"TODOS LOS ESTATUS",
"ULTIMO ESTATUS", 
"FECHA ULTIMO ESTATUS", 
"TIPO DE ENVIO", 
"DEPARTAMENTO DESTINO",
"CIUDAD DESTINO", 
"TRANSPORTADORA", 
"TOTAL DE LA ORDEN", 
"PRECIO FLETE",
"PRECIO PROVEEDOR", 
"COSTO DEL PRODUCTO", 
"PRECIO PROVEEDOR X CANTIDAD",
"PRODUCTO ID", 
"SKU", 
"PRODUCTO", 
"CANTIDAD", 
"TIENDA", 
"ID DE ORDEN DE TIENDA",
"NUMERO DE PEDIDO DE TIENDA", 
"TAGS", 
"FECHA GUIA GENERADA", 
"ID GARANTIA",
"FECHA ENTRADA DINERO - ULTIMA", 
"MONTO PAGADO ORDEN ", 
"VERIFICACION",
"FECHA DEVOLUCION", 
"ID DEVOLUCION"
FROM df
ON CONFLICT ("ID")  

DO UPDATE SET

"ID_ORDER" = EXCLUDED."ID_ORDER",
    "HORA" = EXCLUDED."HORA",
    "FECHA" = EXCLUDED."FECHA",
    "NÚMERO GUIA" = EXCLUDED."NÚMERO GUIA",
    "ULTIMO ESTATUS" = EXCLUDED."ULTIMO ESTATUS",
    "TODOS LOS ESTATUS" = CASE
        WHEN t."ULTIMO ESTATUS" <> EXCLUDED."ULTIMO ESTATUS" THEN
            TRIM(t."TODOS LOS ESTATUS" || ', ' || EXCLUDED."ULTIMO ESTATUS")
        ELSE
            t."TODOS LOS ESTATUS"
    END,
    "FECHA ULTIMO ESTATUS" = CASE
        WHEN t."ULTIMO ESTATUS" <> EXCLUDED."ULTIMO ESTATUS" THEN CURRENT_DATE()
        ELSE t."FECHA ULTIMO ESTATUS"
    END,
    "TIPO DE ENVIO" = EXCLUDED."TIPO DE ENVIO",
    "DEPARTAMENTO DESTINO" = EXCLUDED."DEPARTAMENTO DESTINO",
    "CIUDAD DESTINO" = EXCLUDED."CIUDAD DESTINO",
    "TRANSPORTADORA" = EXCLUDED."TRANSPORTADORA",
    "TOTAL DE LA ORDEN" = EXCLUDED."TOTAL DE LA ORDEN",
    "PRECIO FLETE" = EXCLUDED."PRECIO FLETE",
    "PRECIO PROVEEDOR" = EXCLUDED."PRECIO PROVEEDOR",
    "COSTO DEL PRODUCTO" = EXCLUDED."COSTO DEL PRODUCTO",
    "PRECIO PROVEEDOR X CANTIDAD" = EXCLUDED."PRECIO PROVEEDOR X CANTIDAD",
    "PRODUCTO ID" = EXCLUDED."PRODUCTO ID",
    "SKU" = EXCLUDED."SKU",
    "PRODUCTO" = EXCLUDED."PRODUCTO",
    "CANTIDAD" = EXCLUDED."CANTIDAD",
    "TIENDA" = EXCLUDED."TIENDA",
    "ID DE ORDEN DE TIENDA" = EXCLUDED."ID DE ORDEN DE TIENDA",
    "NUMERO DE PEDIDO DE TIENDA" = EXCLUDED."NUMERO DE PEDIDO DE TIENDA",
    "TAGS" = EXCLUDED."TAGS",
    "FECHA GUIA GENERADA" = EXCLUDED."FECHA GUIA GENERADA",
    "ID GARANTIA" = EXCLUDED."ID GARANTIA",
    "FECHA ENTRADA DINERO - ULTIMA" = EXCLUDED."FECHA ENTRADA DINERO - ULTIMA",
    "MONTO PAGADO ORDEN " = EXCLUDED."MONTO PAGADO ORDEN ",
    "VERIFICACION" = EXCLUDED."VERIFICACION",
    "FECHA DEVOLUCION" = EXCLUDED."FECHA DEVOLUCION",
    "ID DEVOLUCION" = EXCLUDED."ID DEVOLUCION";