INSERT INTO ORDERS_PRODUCT 
SELECT 
    *, 
    NOW() AS update_at 
FROM df_data
ON CONFLICT ("ingestion_id") 
DO UPDATE SET
    "FECHA DE REPORTE" = EXCLUDED."FECHA DE REPORTE",
    "HORA" = EXCLUDED."HORA",
    "FECHA" = EXCLUDED."FECHA",
    "ESTATUS" = EXCLUDED."ESTATUS",
    "TIPO DE ENVIO" = EXCLUDED."TIPO DE ENVIO",
    "NOTAS" = EXCLUDED."NOTAS",
    "TOTAL DE LA ORDEN" = EXCLUDED."TOTAL DE LA ORDEN",
    "GANANCIA" = EXCLUDED."GANANCIA",
    "PRECIO FLETE" = EXCLUDED."PRECIO FLETE",
    "COSTO DEVOLUCION FLETE" = EXCLUDED."COSTO DEVOLUCION FLETE",
    "COMISION" = EXCLUDED."COMISION",
    "% COMISION DE LA PLATAFORMA" = EXCLUDED."% COMISION DE LA PLATAFORMA",
    "NOVEDAD" = EXCLUDED."NOVEDAD",
    "FUE SOLUCIONADA LA NOVEDAD" = EXCLUDED."FUE SOLUCIONADA LA NOVEDAD",
    "HORA DE NOVEDAD" = EXCLUDED."HORA DE NOVEDAD",
    "FECHA DE NOVEDAD" = EXCLUDED."FECHA DE NOVEDAD",
    "SOLUCIÓN" = EXCLUDED."SOLUCIÓN",
    "HORA DE SOLUCIÓN" = EXCLUDED."HORA DE SOLUCIÓN",
    "FECHA DE SOLUCIÓN" = EXCLUDED."FECHA DE SOLUCIÓN",
    "OBSERVACIÓN" = EXCLUDED."OBSERVACIÓN",
    "HORA DE ÚLTIMO MOVIMIENTO" = EXCLUDED."HORA DE ÚLTIMO MOVIMIENTO",
    "FECHA DE ÚLTIMO MOVIMIENTO" = EXCLUDED."FECHA DE ÚLTIMO MOVIMIENTO",
    "ÚLTIMO MOVIMIENTO" = EXCLUDED."ÚLTIMO MOVIMIENTO",
    "CONCEPTO ÚLTIMO MOVIMIENTO" = EXCLUDED."CONCEPTO ÚLTIMO MOVIMIENTO",
    -- 🔑 Actualización del campo de tiempo:
    "update_at" = NOW();