INSERT INTO WALLET 
SELECT
"ID", 
"FECHA", 
"TIPO", 
"MONTO", 
"MONTO PREVIO", 
"ORDEN ID", 
"NUMERO DE GUIA", 
"DESCRIPCIÓN", 
"USUARIO QUE REALIZA EL MOVIMIENTO", 
"CUENTA", 
"CONCEPTO DE RETIRO", 
NOW() AS update_at
FROM df 
ON CONFLICT ("ID") 
DO UPDATE SET
    "FECHA" = EXCLUDED."FECHA",
    "TIPO" = EXCLUDED."TIPO",
    "MONTO" = EXCLUDED."MONTO",
    "MONTO PREVIO" = EXCLUDED."MONTO PREVIO",
    "NUMERO DE GUIA" = EXCLUDED."NUMERO DE GUIA",
    "DESCRIPCIÓN" = EXCLUDED."DESCRIPCIÓN",
    "USUARIO QUE REALIZA EL MOVIMIENTO" = EXCLUDED."USUARIO QUE REALIZA EL MOVIMIENTO",
    "CUENTA" = EXCLUDED."CUENTA",
    "CONCEPTO DE RETIRO" = EXCLUDED."CONCEPTO DE RETIRO",
    "update_at" = NOW();