INSERT INTO WARRANTYS 
SELECT 
    *, 
    NOW() AS update_at,
    TRUE AS isActive
FROM df_data
ON CONFLICT ("ingestion_id") 
DO UPDATE SET
    "ESTADO" = EXCLUDED."ESTADO",
    "72H SIN RESPONDER" = EXCLUDED."72H SIN RESPONDER",
    "RESPUESTA PROVEEDOR" = EXCLUDED."RESPUESTA PROVEEDOR",
    "RECOLECCION CREADA" = EXCLUDED."RECOLECCION CREADA",
    "NUMERO DE GUIA O ORDEN DE RECOLECCION" = EXCLUDED."NUMERO DE GUIA O ORDEN DE RECOLECCION",
    "update_at" = NOW(),
    "isActive" = TRUE