SELECT

CAST("FECHA DE REPORTE" AS DATE) as "FECHA_REPORTE",
"ID",
"ORDEN DE DROPSHIPPER" AS "ORDEN_DROPSHIPPER",
CAST("HORA" AS TIME) AS "HORA",
"NÚMERO GUIA" AS "NUMERO_GUIA",
"ESTATUS",
"TIPO DE ENVIO" AS "TIPO_ENVIO",
"DEPARTAMENTO DESTINO" AS "DEPARTAMENTO_DESTINO",
"CIUDAD DESTINO" AS "CIUDAD_DESTINO",
"NOTAS",
"TRANSPORTADORA",
"TOTAL DE LA ORDEN",
CASE WHEN "GANANCIA" IS NULL THEN 0 ELSE "GANANCIA" END AS "GANANCIA",
"PRECIO FLETE" AS "PRECIO_FLETE",
CASE WHEN "COSTO DEVOLUCION FLETE" IS NULL THEN 0 ELSE "COSTO DEVOLUCION FLETE" AS "COSTO_DEVOLUCION_FLETE",
CASE WHEN CAST("COMISION" AS FLOAT) IS NULL THEN 0 ELSE CAST("COMISION" AS FLOAT) AS "COMISION",
"NOVEDAD",
"FUE SOLUCIONADA LA NOVEDAD" AS "FUE_SOLUCIONADA",
CAST("HORA DE NOVEDAD" AS TIME) AS "HORA_NOVEDAD",
CAST("FECHA DE NOVEDAD" AS DATE) AS "FECHA_NOVEDAD",
"SOLUCIÓN",
CAST("HORA DE SOLUCIÓN" AS TIME) AS "HORA_SOLUCION",
CAST("FECHA DE SOLUCIÓN" AS DATE) AS "FECHA_SOLUCION",
"OBSERVACIÓN",
"HORA DE ÚLTIMO MOVIMIENTO" AS "HORA_ULTIMO_MOVIMIENTO"

 FROM RAW_Orders