CREATE TABLE WALLET (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "FECHA" DATE, 
    "TIPO" VARCHAR,
    "MONTO" DOUBLE,
    "MONTO PREVIO" DOUBLE,
    "ORDEN ID" VARCHAR,
    "NUMERO DE GUIA" VARCHAR,
    "DESCRIPCIÓN" VARCHAR,
    "USUARIO QUE REALIZA EL MOVIMIENTO" VARCHAR,
    "CUENTA" VARCHAR,
    "CONCEPTO DE RETIRO" VARCHAR,
    "ingestion_id" VARCHAR NOT NULL,
    "ingestion_timestamp" TIMESTAMP
);