WITH FINAL_WALLET AS (
SELECT 
FECHA,
CASE 
	WHEN "TIPO" = 'ENTRADA' 
	THEN MONTO 
	ELSE MONTO *-1 
END AS MONTO,
"NUMERO DE GUIA"


FROM WALLET
)

SELECT
op."ID",
op."HORA",
op."FECHA",
op."NÚMERO GUIA",
op."ESTATUS",
op."ESTATUS" AS "ULTIMO ESTATUS",
NOW() AS "FECHA ULTIMO ESTATUS",
op."TIPO DE ENVIO",
op."DEPARTAMENTO DESTINO",
op."CIUDAD DESTINO",
op."TRANSPORTADORA",
op."TOTAL DE LA ORDEN",
op."PRECIO FLETE",
op."PRECIO PROVEEDOR",
0 AS  "COSTO DEL PRODUCTO",
op."PRECIO PROVEEDOR X CANTIDAD",
op."PRODUCTO ID",
op."SKU",
op."PRODUCTO",
op."CANTIDAD",
o."TIENDA",
op."ID DE ORDEN DE TIENDA",
op."NUMERO DE PEDIDO DE TIENDA",
op."TAGS",
op."FECHA GUIA GENERADA",
w."ID GARANTIA",
MAX(wt."FECHA") AS "FECHA ENTRADA DINERO - ULTIMA",
SUM(wt."MONTO") AS "MONTO PAGADO ORDEN ",

FROM ORDERS  o

INNER JOIN ORDERS_PRODUCT op
ON op."ID" = o."ID"
LEFT JOIN WARRANTYS w 
ON w."ID ORDEN" = op."ID" AND w."ID PRODUCTO" = op."PRODUCTO ID"
LEFT JOIN FINAL_WALLET wt
ON wt."NUMERO DE GUIA" = o."NÚMERO GUIA"
LEFT JOIN DEVOLUTION d 
ON d."NUMERO DE GUIA" = op."NÚMERO GUIA"

GROUP BY op."ID", op."HORA", op."FECHA", op."NÚMERO GUIA", op."ESTATUS", "ULTIMO ESTATUS", "FECHA ULTIMO ESTATUS", 
op."TIPO DE ENVIO", op."DEPARTAMENTO DESTINO", op."CIUDAD DESTINO", op."TRANSPORTADORA", op."TOTAL DE LA ORDEN", 
op."PRECIO FLETE", op."PRECIO PROVEEDOR", "COSTO DEL PRODUCTO", op."PRECIO PROVEEDOR X CANTIDAD", op."PRODUCTO ID",
op."SKU", op."PRODUCTO", op."CANTIDAD", o."TIENDA", op."ID DE ORDEN DE TIENDA", op."NUMERO DE PEDIDO DE TIENDA", 
op."TAGS", op."FECHA GUIA GENERADA", w."ID GARANTIA";