WITH FINAL_WALLET AS (
SELECT 
FECHA,
CASE 
	WHEN "TIPO" = 'ENTRADA' 
	THEN MONTO 
	ELSE MONTO *-1 
END AS MONTO,
"NUMERO DE GUIA"::VARCHAR AS "NUMERO DE GUIA" 


FROM WALLET
)




SELECT
op."ID",
op."HORA",
op."FECHA",
op."NÚMERO GUIA",
op."ESTATUS",
op."ESTATUS" AS "ULTIMO ESTATUS",
NOW() AS "FECHA ULTIMO ESTATUS",
op."TIPO DE ENVIO",
op."DEPARTAMENTO DESTINO",
op."CIUDAD DESTINO",
op."TRANSPORTADORA",
op."TOTAL DE LA ORDEN",
op."PRECIO FLETE",
op."PRECIO PROVEEDOR",
0 AS  "COSTO DEL PRODUCTO",
op."PRECIO PROVEEDOR X CANTIDAD",
op."PRODUCTO ID",
op."SKU",
op."PRODUCTO",
op."CANTIDAD",
o."TIENDA",
op."ID DE ORDEN DE TIENDA",
op."NUMERO DE PEDIDO DE TIENDA",
o."TAGS",
op."FECHA GUIA GENERADA",
w."ID GARANTIA",
MAX(wt."FECHA") AS "FECHA ENTRADA DINERO - ULTIMA",
COALESCE(SUM(wt."MONTO"),0) AS "MONTO PAGADO ORDEN ",

CASE
	WHEN op."ESTATUS" = 'ENTREGADO' AND "PRECIO PROVEEDOR X CANTIDAD" = SUM(wt."MONTO") THEN 'OK'
	WHEN op."ESTATUS" = 'ENTREGADO' AND "PRECIO PROVEEDOR X CANTIDAD" <> SUM(wt."MONTO") THEN 'POR REVISAR'
	WHEN op."ESTATUS" = 'DEVUELTO' AND d."FECHA" IS NULL THEN 'POR REVISAR'
	WHEN op."ESTATUS" IN ('EN TRANSITO','EN DEVOLUCION') THEN 'PENDIENTE' 
	WHEN op."ESTATUS" = 'DEVUELTO' AND d."FECHA" IS NOT NULL THEN 'OK'
	ELSE 'SIN DEFINIR'
END AS "VERIFICACION",
d."FECHA" AS "FECHA DEVOLUCION",
d."ID" AS "ID DEVOLUCION"



FROM ORDERS_PRODUCT  op

LEFT JOIN ORDERS o
ON op."ID" = o."ID"

LEFT JOIN WARRANTYS w 
ON w."ID ORDEN" = op."ID" AND w."ID PRODUCTO" = op."PRODUCTO ID"

LEFT JOIN FINAL_WALLET wt
ON wt."NUMERO DE GUIA" = o."NÚMERO GUIA"

LEFT JOIN DEVOLUTION d 
ON d."NUMERO DE GUIA" = op."NÚMERO GUIA"

GROUP BY op."ID", op."HORA", op."FECHA", op."NÚMERO GUIA", op."ESTATUS", "ULTIMO ESTATUS", "FECHA ULTIMO ESTATUS", 
op."TIPO DE ENVIO", op."DEPARTAMENTO DESTINO", op."CIUDAD DESTINO", op."TRANSPORTADORA", op."TOTAL DE LA ORDEN", 
op."PRECIO FLETE", op."PRECIO PROVEEDOR", "COSTO DEL PRODUCTO", op."PRECIO PROVEEDOR X CANTIDAD", op."PRODUCTO ID",
op."SKU", op."PRODUCTO", op."CANTIDAD", o."TIENDA", op."ID DE ORDEN DE TIENDA", op."NUMERO DE PEDIDO DE TIENDA", 
o."TAGS", op."FECHA GUIA GENERADA", w."ID GARANTIA",d."FECHA",d."ID",op."ID_ORDER_PRODUCT";